// ----------------------------------------------------------------------------
//   The confidential and proprietary information contained in this file may
//   only be used by a person authorized under and to the extent permitted
//   by a subsisting licensing agreement from ARM Limited or its affiliates.
//
//          (C)COPYRIGHT 2018 ARM Limited or its affiliates.
//              ALL RIGHTS RESERVED
//
//   This entire notice must be reproduced on all copies of this file
//   and copies of this file may only be made by a person if such person is
//   permitted to do so under the terms of a subsisting license agreement
//   from ARM Limited or its affiliates.
// ----------------------------------------------------------------------------
package com.arm.mbed.sda.proxysdk.http;

public class FieldMessageEntry implements Comparable<FieldMessageEntry> {

    private String field;
    private String message;

    public FieldMessageEntry() {
    }

    public FieldMessageEntry(String key, String value) {
        this.field = key;
        this.message = value;
    }

    public String getField() {
        return field;
    }

    public void setField(String field) {
        this.field = field;
    }

    public String getMessage() {
        return message;
    }

    public void setMessage(String message) {
        this.message = message;
    }

    //This func is for sorting
    @Override
    public int compareTo(FieldMessageEntry fieldMessageEntry) {

        String compareMessage = fieldMessageEntry.getMessage();

        //ascending order
        return this.message.compareTo(compareMessage);

        //descending order
        //return compareKey - this.key;
    }

    /* --- Hash Code ---
     * 
     * Generated by Eclipse.
     * 
     * @see java.lang.Object#hashCode()
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((field == null) ? 0 : field.hashCode());
        result = prime * result + ((message == null) ? 0 : message.hashCode());
        return result;
    }


    @Override
    public boolean equals(Object obj) {
        // just for performance..  if it's the actual same object
        if (this == obj) {
            return true;
        }

        if (obj == null) {
            return false;
        }
        if (!FieldMessageEntry.class.isAssignableFrom(obj.getClass())) {
            return false;
        }

        final FieldMessageEntry other = (FieldMessageEntry) obj;
        if ((this.field == null) ? (other.field != null) : !this.field.equals(other.field)) {
            return false;
        }
        if ((this.message == null) ? (other.message != null) : !this.message.equals(other.message)) {
            return false;
        }
        return true;
    }
}
