// ----------------------------------------------------------------------------
// Copyright 2017-2019 ARM Ltd.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// ----------------------------------------------------------------------------
package com.arm.mbed.sda.proxysdk.http;

public class FieldMessageEntry implements Comparable<FieldMessageEntry> {

    private String field;
    private String message;

    public FieldMessageEntry() {
    }

    public FieldMessageEntry(String key, String value) {
        this.field = key;
        this.message = value;
    }

    public String getField() {
        return field;
    }

    public void setField(String field) {
        this.field = field;
    }

    public String getMessage() {
        return message;
    }

    public void setMessage(String message) {
        this.message = message;
    }

    //This func is for sorting
    @Override
    public int compareTo(FieldMessageEntry fieldMessageEntry) {

        String compareMessage = fieldMessageEntry.getMessage();

        //ascending order
        return this.message.compareTo(compareMessage);

        //descending order
        //return compareKey - this.key;
    }

    /* --- Hash Code ---
     * 
     * Generated by Eclipse.
     * 
     * @see java.lang.Object#hashCode()
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((field == null) ? 0 : field.hashCode());
        result = prime * result + ((message == null) ? 0 : message.hashCode());
        return result;
    }


    @Override
    public boolean equals(Object obj) {
        // just for performance..  if it's the actual same object
        if (this == obj) {
            return true;
        }

        if (obj == null) {
            return false;
        }
        if (!FieldMessageEntry.class.isAssignableFrom(obj.getClass())) {
            return false;
        }

        final FieldMessageEntry other = (FieldMessageEntry) obj;
        if ((this.field == null) ? (other.field != null) : !this.field.equals(other.field)) {
            return false;
        }
        if ((this.message == null) ? (other.message != null) : !this.message.equals(other.message)) {
            return false;
        }
        return true;
    }
}
